In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import load_iris
data = load_iris()
data.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [5]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
df = pd.DataFrame(data.data, columns = data.feature_names)
df['target'] = data.target

In [9]:
df.sample(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
138                6.0               3.0                4.8               1.8   
124                6.7               3.3                5.7               2.1   

     target  
138       2  
124       2

In [10]:
df.target.unique()

array([0, 1, 2])

In [11]:
#for binary classification
# df_final =  df[df['target'] != 2]

In [12]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [13]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [14]:
#model training
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter = 300)
classifier

LogisticRegression(max_iter=300)

In [15]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=300)

In [16]:
y_pred = classifier.predict(X_test)

In [17]:
classifier.predict_proba(X_test) 

array([[9.84756885e-01, 1.52430933e-02, 2.17110119e-08],
       [2.75828385e-01, 7.21527683e-01, 2.64393201e-03],
       [6.28307303e-03, 8.89254472e-01, 1.04462455e-01],
       [9.85522329e-01, 1.44776082e-02, 6.32455696e-08],
       [1.18098818e-06, 1.89949900e-02, 9.81003829e-01],
       [4.52451115e-03, 6.27720946e-01, 3.67754543e-01],
       [1.46978033e-04, 1.27787036e-01, 8.72065986e-01],
       [9.57856361e-01, 4.21424117e-02, 1.22679787e-06],
       [9.69596820e-01, 3.04028712e-02, 3.08634667e-07],
       [9.74403455e-06, 2.70538004e-02, 9.72936456e-01],
       [1.89794127e-02, 8.79782627e-01, 1.01237960e-01],
       [9.66525611e-01, 3.34739470e-02, 4.41808494e-07],
       [4.71940086e-06, 3.10164916e-02, 9.68978789e-01],
       [7.14680872e-03, 8.01803376e-01, 1.91049815e-01],
       [6.97670102e-03, 7.49198895e-01, 2.43824404e-01],
       [9.88113894e-01, 1.18860390e-02, 6.70431338e-08],
       [2.25070840e-02, 9.37032308e-01, 4.04606083e-02],
       [1.09511320e-02, 6.81770

In [19]:
#Evaluation metrics
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
#roc auc score can only be calculated for binary classification

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

